AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: case
  IndentOneStep: true

Style/Documentation:
  Enabled: false

Layout/FirstParameterIndentation:
  IndentationWidth: 4

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - '*.rake'
    - 'Rakefile'

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/SignalException:
  EnforcedStyle: semantic
